Step2 컬렉션뷰로 사진 보관함의 사진 표시
codesquad-memeber-2020/photos-3 pull request #17
Opened 2020-03-17 14:05 UTC by seizze

각자 기능 구현을 하던 중 사진 라이브러리를 옵저빙하는 기능은 사진 라이브러리를 컬렉션뷰에 보여주는 기능에 대한 의존성이 필요했기 때문에 사진 라이브러리를 컬렉션뷰에 보여주는 기능을 완료 하여 feature/display_photo에 머지된 후에 옵저빙하는 기능을 작업하던 브랜치에 feature/display_photo의 내용을 머지하였습니다. 충돌이 발생하여 페어로 해결하였습니다.

Cell reuse identifier를 하드코딩하지 않기 위해 ReusableView 프로토콜을 선언하고 CollectionViewCell에서 이 프로토콜을 채택하였습니다. UICollectionView에 extension을 추가하여 cell deque 메서드를 간소화하였습니다. 이전에 본 동영상을 참고하였습니다.

ViewController가 Photos에 의존하지 않도록 DataSource 역할을 하는 객체를 새로 만들어 분리하였습니다.

실제 디바이스에 올려서 확인 결과, 앱을 킬 때 느리진 않았습니다.

참고한 동영상 링크: <https://academy.realm.io/posts/appbuilders-natasha-muraschev-practical-protocol-oriented-programming/>

Closes #2 #3 #7 #8 #9 #13 #15

2020-03-17 14:47 UTC, godrm commented
내일부터는 충돌이 발생하지 않도록 더 자주 합쳐보면 좋을 것 같습니다. 머지하려는 단위가 클 수록 충돌은 많이 발생하니까요.

2020-03-17 14:59 UTC, godrm requested changes
좋은 시도였던 것 같습니다. 다음 피드백을 확인해보세요.

2020-03-17 14:59 UTC, godrm commented on PhotosApp/PhotosApp/Model/PhotoDataSource.swift
> +        delegate?.photoLibraryDidUpdate()
DataSource 역할을 하는 모델이 다시 또 delegate를 찾고 있는 것은 좋은 구조가 아닙니다. 
모델은 1:1 관계로 한 곳에서만 참조하지 않을 가능성이 높습니다. 
그래서 델리게이트 보다는 NotificationCenter 같은 1:n 구조를 많이 쓰는 편입니다.

2020-03-17 14:59 UTC, godrm commented on PhotosApp/PhotosApp/Util/UICollectionViewExtensions.swift
> +            fatalError("Could not dequeue cell with identifier: \(T.reuseIdentifier)")
reuseIdentifier를 활용하기 위한 방식을 도입한 부분은 좋습니다만 두 가지 정도는 주의하세요.
- `dequeueReusableCell<T: UICollectionViewCell>(for indexPath: IndexPath) -> T` 에서 generic T를 선언했으면 호출할 때도 타입을 명시해주는 게 좋을 것 같습니다. 
- `guard else {}` 에서 fatalError() 보다는 흐름 제어를 할 수 있도록 다른 방법이 있는 게 안전합니다. 실수로 셀이 안 만들어지면 앱이 멈춰버리는 데 그걸 강제할 필요는 없습니다. fatalError는 정말 개발자가 손쓸 수 없을 만큼 치명적인 에러인 경우만 쓰세요.

2020-03-17 14:59 UTC, godrm commented on PhotosApp/PhotosApp/Model/PhotoDataSource.swift
> +           let cell = collectionView.dequeueReusableCell(for: indexPath) as PhotoCell
결국에 PhotoCell 로 타입캐스팅을 할꺼라면 reuseIdentifier를 줄인 효과가 그다지 없는 것 같습니다. PhotoCell에 reuseIdentifier가 있다면 `PhotoCell.reuseIdentifier`만 명시해도 되는데 더 복잡해진 건 아닐까요?

2020-03-17 14:59 UTC, godrm commented on PhotosApp/PhotosApp/View/PhotoCell.swift
> +    var representedAssetIdentifier: String!
이 속성은 어떤 의도인건가요?

2020-03-17 14:59 UTC, godrm commented on PhotosApp/PhotosApp/ViewController.swift
> +        DispatchQueue.main.sync { collectionView.reloadData() }
매번 모든 사진을 다시 로딩해야 하는 구조인가요?

2020-03-18 06:16 UTC, seizze commented on PhotosApp/PhotosApp/Model/PhotoDataSource.swift
> +        delegate?.photoLibraryDidUpdate()
네 NotificationCenter를 이용하도록 변경하였습니다!

2020-03-18 06:16 UTC, seizze commented on PhotosApp/PhotosApp/ViewController.swift
> +        DispatchQueue.main.sync { collectionView.reloadData() }
뷰 컨트롤러에서는 변경된 데이터를 받아서 컬렉션뷰를 업데이트하도록 변경하였습니다.

2020-03-18 06:17 UTC, Limwin94 commented on PhotosApp/PhotosApp/Model/PhotoDataSource.swift
> +           let cell = collectionView.dequeueReusableCell(for: indexPath) as PhotoCell
위의 코멘트까지 합해서 리팩토링 진행하였습니다. 
- extension으로 dequeueReusableCell 메소드를 커스텀하는 것을 삭제하였고 ```PhotoCell.reuseIdentifier```만 명시하도록 변경하였습니다.
- guard문에서도 fatalError대신 PhotoCell을 생성하여 반환하는 코드로 변경하였습니다.

2020-03-18 06:18 UTC, Limwin94 commented on PhotosApp/PhotosApp/View/PhotoCell.swift
> +    var representedAssetIdentifier: String!
처음에 asset의 identifier을 저장할 용도로 사용하였으나 삭제를 못한채로 pr보냈습니다. 지금은 삭제하였습니다!

2020-03-18 06:20 UTC, seizze commented
네 오늘부터는 충돌이 발생하지 않도록 더 자주 합쳐보도록 하겠습니다.ㅎㅎ

2020-03-18 07:05 UTC, godrm commented
네 머지하셔도 될 것 같습니다. 수고하셨습니다.

2020-03-18 07:07 UTC, merged